### ISSUE TITLE
An HTTP header to allow profiling of document scripts by foreign origins?

### ISSUE THREAD

**Issue by vdjeric** [WICG/js-self-profiling#1]
Question asked by msoInit on the [WICG discourse thread](https://discourse.wicg.io/t/proposal-an-api-to-allow-webpage-javascript-to-profile-its-own-performance/2818/3?u=vdjeric)

> Should there be header similar to Timing-Allow-Origin that lets a third party permit profiling of its scripts (even if they’re not same-origin)?

**Comment by vdjeric** [comment]
That sounds like a good idea, but I will let others chime in before adding it to the proposal, since I haven’t thought enough about the privacy implications.

What use case are you envisioning for this? Third party IFrame ads or something else?

**Comment by igrigorik** [comment]
I'd encourage you to spend some time carefully thinking through this part of the spec first, before you invest too much time into other pieces. FB is amongst a very small set of sites on the web that is effectively exclusively powered by 1P content, which makes exposing traces simple to reason about.

Your average site on the web does not fall into the above category, with dozens of 3P scripts interleaved in the trace. Exposing stacks of 3P scripts could easily expose security and privacy risks to the user and the 3P provider: you need this to be opt-in. Given that, what does that look like, and what are the implications for accuracy and viability of the trace? It's not clear to me that hiding the stack info would hide all the information leaks. 

Similarly, how does content in iframes get accounted for  — in Chrome with site isolation we may have a a workaround here, but it's not clear to me what other browsers would do here.

**Comment by acomminos** [comment]
Thanks for the feedback @igrigorik! We spoke at TPAC regarding requiring CORS in order to obtain stack frames from 3P scripts, and that's now represented in the explainer.

Re: iframes, that's correct that site isolation or possibly some form of timer fuzzing will be required in order to avoid attacks here. FWIW, FF is planning on shipping site isolation as well.

**Comment by acomminos** [comment]
Closed as the CORS requirement should address this issue.
