### ISSUE TITLE
Add a header/metadata hint for JavaScript profiling

### ISSUE THREAD

**Issue by dominiccooney** [WICG/js-self-profiling#13]
Implementations might produce more accurate results if they know that the page will be profiling. For example an implementation might opt to keep metadata for symbolification around instead of paying extra to create it lazily.

See also Issue #2, which is about metadata for startup profiling.

**Comment by acomminos** [comment]
This ended up turning into [document policy integration](https://github.com/WICG/js-self-profiling/commit/07db2656b6f25792a3acd596c9fd24972f1980a9)! Closing.
