### ISSUE TITLE
"int" is not a type

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/js-self-profiling#18]
Just a heads up the "int" is not a WebIDL type (why the ReSpec is showing red errors). According to the [WebIDL spec](https://heycam.github.io/webidl/#idl-types):

> The following types are known as integer types: byte, octet, short, unsigned short, long, unsigned long, long long and unsigned long long.

Kindly please choose the most suitable type for each... or just go "unsigned long long" if you want something that more or less matches a JS number.

**Comment by marcoscaceres** [comment]
Same with `bool` ... use boolean :)

**Comment by acomminos** [comment]
Fixed, thank you! :)
