### ISSUE TITLE
No processing model for initializing ProfilerTrace

### ISSUE THREAD

**Issue by annevk** [WICG/js-self-profiling#32]
It defines some members, but nothing defines how these are initialized.

**Comment by acomminos** [comment]
Yeah, the initialization logic in the spec is pretty sketchy -- as you noticed, the fields themselves are constrained in the definitions, but we don't construct the samples in any explicit logic. This was easier to do earlier on for jotting down expectations, but we should adopt a formal processing model.

**Comment by acomminos** [comment]
Hey @annevk, I've gone ahead and added a [draft processing model](https://wicg.github.io/js-self-profiling/#processing-model) to the spec -- the expected behaviour should be more straightforward now :)
