### ISSUE TITLE
ProfilerFrame stability

### ISSUE THREAD

**Issue by littledan** [WICG/js-self-profiling#34]
I'm curious about the details of the [ProfilerFrame dictionary](https://wicg.github.io/js-self-profiling/#the-profilerframe-dictionary). This seems to include information about the line and column. I'm a little concerned that this could be brittle with the use of sourcemaps, but I don't have a strong alternative in mind. (Maybe the function identity could be included, but then this couldn't be transmitted over the network. But even the function name could be helpful.)

**Comment by acomminos** [comment]
I'd like to know a bit more about the brittleness that you mention -- do you mean the traces would only be useful when strongly coupled with the sourcemap?

**Comment by littledan** [comment]
Yes. (I don't see this as a show-stopper issue, but a reason to consider including the function name like some of the prior art you cited does, as this adds some form of resilience.)

**Comment by acomminos** [comment]
Ah, so the `name` field of `ProfilerFrame` actually does contain the function's name, set via the associated function instance's [name property](https://tc39.es/ecma262/#sec-function-instances-name). It's defined in the section below the `ProfilerFrame` IDL.

**Comment by littledan** [comment]
Oh, I'm not sure how I missed that. Maybe there's nothing to do for this issue, so closing it.
