### ISSUE TITLE
why does `profile()` return a promise?

### ISSUE THREAD

**Issue by ljharb** [WICG/js-self-profiling#37]
What async work is being set done when i ask to *begin* a profiling session? Wouldn't awaiting it potentially add additional delay between the fulfillment of the promise, and the start of the code I wish to measure?

**Comment by acomminos** [comment]
This is a good point -- this was introduced to give UAs flexibility to do additional work before profiling (e.g. spin up a new thread), but there's sufficient asynchrony permitted in the periodic sampling such that this may not be necessary.
