### ISSUE TITLE
Frame w/o enclosing function

### ISSUE THREAD

**Issue by bmeck** [WICG/js-self-profiling#39]
What happens if a Script or Module is doing some work and shows up in sampling? I'm guessing the `name` is expected to be `null`?

**Comment by acomminos** [comment]
Yup, that's correct -- we'll have no function instance associated with the frame, and thus provide `null` as the value for `name` (as per the definition of `name`). The `null` function object of the running execution context for the script/module is set in [this part of ECMA-262](https://tc39.es/ecma262/#table-state-components-for-all-execution-contexts):

> If this execution context is evaluating the code of a function object, then the value of this component is that function object. If the context is evaluating the code of a Script or Module, the value is null.

**Comment by acomminos** [comment]
Closing, since I believe this is handled by the section linked above.
