### ISSUE TITLE
Define things in terms of HTML's script concept

### ISSUE THREAD

**Issue by annevk** [WICG/js-self-profiling#44]
I suspect a bunch of things here ought to depend on https://html.spec.whatwg.org/#concept-script. E.g., you cannot talk about the response of a script, but "muted errors" covers what you want. (Perhaps that should be renamed if it's going to be used for this though.)

cc @domenic

**Comment by acomminos** [comment]
This is a great suggestion. I've gone ahead and implemented the `CORS-same-origin` enforcement via the Script's muted errors for now, as well as formalized the URL of frames to use the Script's base URL -- let me know your thoughts!

**Comment by acomminos** [comment]
Closing this issue, I think we leverage script concepts wherever applicable now.
