### ISSUE TITLE
Should built-in function object execution always be observable?

### ISSUE THREAD

**Issue by acomminos** [WICG/js-self-profiling#51]
Currently, the execution of built-in function objects is always observable in the [frame processing model](https://wicg.github.io/js-self-profiling/#dfn-get-a-frame-id) (even when called by opaque cross-origin scripts) under the assumption that existing builtins could be overridden with ease to provide similar instrumentation (as mentioned in one of the [security reviews](https://gist.github.com/shhnjk/57e305df82e8200b857fc32d24ddc877#get-information-of-cross-origin-no-cors-scripts)).

@yoavweiss [raised a good point on blink-dev](https://groups.google.com/a/chromium.org/g/blink-dev/c/7K7Qt7aRJ8s/m/JcRGspXtAwAJ) that it's often hard to otherwise observe built-in execution, and there are a [few good ways to identify](https://www.slideshare.net/CharlesVazac/how-to-identify-bad-third-parties-on-your-page-midwest-js-public) when builtins are instrumented. These methods do not seem airtight, but the API certainly makes it easier to observe built-in calls.

The benefit of showing built-ins invoked by opaque cross-origin scripts is small, so perhaps we should consider hiding them if the parent execution context does not have its frame included in traces.

cc @shhnjk

**Comment by shhnjk** [comment]
Sounds good to me :)

**Comment by acomminos** [comment]
Sorry, meant to ask -- @shhnjk, did this come up in the WebAppSec discussion of your security review?

**Comment by shhnjk** [comment]
No, but from security point of view, it does make sense to hide built-in function’s execution, if it’s not invoked by same-origin or CORS satisfied scripts.
